project:
  type: website
  output-dir: docs

website:
  title: "KD's Blog"
  site-url: "https://kaivalya1997.github.io/blog"
  description: "Exploring the frontiers of Mathematics and Artificial Intelligence"
  favicon: favicon.ico
  image: "profile.jpg"
  twitter-card:
    creator: "@Kaivalya1997"
    image: "profile.jpg"
  open-graph: true
  page-navigation: true
  back-to-top-navigation: true
  
  navbar:
    background: primary
    search: true
    pinned: true
    left:
      - text: "Home"
        href: index.qmd
      - text: "About"
        href: about.qmd
    right:
      # === SOCIAL LINKS: Update with your profiles ===
      - icon: github
        href: https://github.com/Kaivalya1997
        aria-label: GitHub
      # - icon: twitter
      #   href: https://twitter.com/Kaivalya1997
      #   aria-label: Twitter
      - icon: linkedin
        href: https://www.linkedin.com/in/kaivalya-dabhadkar-384a47151
        aria-label: LinkedIn
          
  page-footer:
    center: |
      Copyright © Kaivalya Dabhadkar
    background: light
    
format:
  html:
    theme: [litera, theme-light.scss]
    css: styles.css
    toc: true
    toc-depth: 3
    toc-location: right
    code-copy: true
    code-overflow: wrap
    link-external-icon: true
    link-external-newwindow: true
    smooth-scroll: true
    anchor-sections: true
    footnotes-hover: true
    citations-hover: true
    page-layout: article
    grid:
      sidebar-width: 250px
      body-width: 900px
      margin-width: 250px
      gutter-width: 1.5rem
    fontsize: 1rem
    linestretch: 1.7
    mainfont: "Inter, -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif"
    monofont: "Fira Code, 'SF Mono', Monaco, 'Courier New', monospace"
    highlight-style: github
    html-math-method: mathjax
    mathjax: "https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-svg.js"
    include-in-header:
      text: |
        <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=5.0, user-scalable=yes">
        <meta name="mobile-web-app-capable" content="yes">
        <meta name="apple-mobile-web-app-capable" content="yes">
        <meta name="apple-mobile-web-app-status-bar-style" content="default">
        <meta name="format-detection" content="telephone=no">
        <script>
          window.MathJax = {
            tex: {
              inlineMath: [['$', '$'], ['\\(', '\\)']],
              displayMath: [['$$', '$$'], ['\\[', '\\]']],
              processEscapes: true,
              processEnvironments: true,
              tags: 'ams'
            },
            options: {
              processHtmlClass: 'tex2jax_process|mathjax_process|math|output',
              enableExplorer: false
            },
            svg: {
              fontCache: 'global',
              scale: 1,
              minScale: 0.5,
              mtextInheritFont: false,
              merrorInheritFont: true,
              mathmlSpacing: false,
              skipAttributes: {},
              exFactor: 0.5,
              displayAlign: 'center',
              displayIndent: '0'
            }
          };
        </script>
        <script>
          // Attach original TeX to MathJax containers and ensure copy-to-clipboard includes TeX
          document.addEventListener('DOMContentLoaded', function () {
            if (window.MathJax && MathJax.startup && MathJax.startup.promise) {
              MathJax.startup.promise.then(function () {
                try {
                  var items = MathJax.startup.document.getMathItemsWithin(document.body);
                  items.forEach(function (item) {
                    var tex = item.math;
                    var container = item.typesetRoot; // <mjx-container>
                    if (container && tex) {
                      container.setAttribute('data-tex', tex);
                      var isDisplay = container.getAttribute('display') === 'true';
                      container.setAttribute('data-tex-wrapper', isDisplay ? '$$' : '$');
                    }
                  });
                } catch (e) { /* no-op */ }
              });
            }

            document.addEventListener('copy', function (e) {
              var sel = window.getSelection();
              if (!sel || sel.rangeCount === 0) { return; }
              var range = sel.getRangeAt(0);
              var fragment = range.cloneContents();
              var tmp = document.createElement('div');
              tmp.appendChild(fragment);
              var mjx = tmp.querySelectorAll('mjx-container');
              if (!mjx.length) { return; } // fall back to default behavior
              mjx.forEach(function (node) {
                var tex = node.getAttribute('data-tex');
                var wrap = node.getAttribute('data-tex-wrapper') || '$';
                var replacement = document.createTextNode(tex ? (wrap + tex + wrap) : (node.innerText || ''));
                node.parentNode.replaceChild(replacement, node);
              });
              var text = tmp.innerText;
              e.clipboardData.setData('text/plain', text);
              e.preventDefault();
            });
          });
        </script>
    
execute:
  freeze: auto
  
comments:
  utterances:
    repo: Kaivalya1997/blog-comments
    theme: github-light
    issue-term: pathname



